(()=>{
"use strict";
const $=id=>document.getElementById(id),arr=v=>Array.isArray(v)?v:[],txt=v=>String(v??"").trim();
const norm=v=>txt(v).toLocaleLowerCase("de").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");
const el=(tag,cls,value)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(value!==undefined)n.textContent=txt(value);return n};
const add=(parent,tag,cls,value)=>{const n=el(tag,cls,value);parent.appendChild(n);return n};
const pkey=p=>txt(p?.teilnehmerId)||`name:${norm(p?.name)}`,value=i=>[i?.wert,i?.einheit].filter(v=>txt(v)).join(" ");
const bestNames=item=>arr(item?.halter).length?item.halter.map(x=>x.name).filter(Boolean).join(" / "):txt(item?.name);
let data=null;
function row(label,content){const n=el("div","row");add(n,"span","",label);add(n,"strong","",content||"–");return n}
const empty=message=>el("div","empty",message);
function fill(select,items,placeholder){select.replaceChildren();const first=el("option","",placeholder);first.value="";select.appendChild(first);for(const item of items){const option=el("option","",item.label);option.value=item.value;select.appendChild(option)}}
function renderHonors(){const target=$("honorGrid"),items=arr(data.ehrenchampions).filter(x=>x?.bestaetigt!==false&&txt(x?.name)&&txt(x?.titel)).sort((a,b)=>txt(b.jahr||b.saison).localeCompare(txt(a.jahr||a.saison),"de"));target.replaceChildren();if(!items.length)return target.appendChild(empty("Noch keine bestätigten Ehrenchampions vorhanden."));for(const item of items){const card=el("article","honor-card");add(card,"h3","",item.titel);add(card,"strong","",item.name);add(card,"p","",[item.saison||item.jahr,item.punkte!==undefined?`${item.punkte} Punkte`:null].filter(Boolean).join(" · "));target.appendChild(card)}}
function renderRecords(){const target=$("recordGrid");target.replaceChildren();if(!arr(data.ewigeRekorde).length)return target.appendChild(empty("Noch keine absoluten Rekorde vorhanden."));for(const item of data.ewigeRekorde){const card=el("article","record-card");add(card,"h3","",item.label);add(card,"strong","record-value",value(item));const holders=add(card,"div","record-holders");for(const holder of arr(item.halter))add(holders,"p","",`${holder.name}${holder.saison?` · ${holder.saison}`:""}`);if(arr(item.entwicklung).length>1)add(card,"p","record-history",`${item.entwicklung.length} bestätigte Rekordstände dokumentiert`);target.appendChild(card)}}
const season=()=>arr(data.saisons).find(x=>x.id===$("seasonSelect").value)||arr(data.saisons)[0]||null;
function renderSeason(){const target=$("seasonContent"),item=season();target.replaceChildren();if(!item)return target.appendChild(empty("Noch keine abgeschlossene Saison archiviert."));const banner=el("div","season-banner");for(const block of [{label:"Gesamtchampion",entry:item.gesamtChampion},{label:"Gesamt-Team-Sieger",entry:item.gesamtTeamSieger}]){const card=el("article","summary-card");add(card,"h3","",block.label);add(card,"strong","",block.entry?.name||"Nicht vergeben / nicht erfasst");add(card,"p","",block.entry?.punkte!==undefined?`${block.entry.punkte} Punkte`:item.label);banner.appendChild(card)}target.appendChild(banner);add(target,"h3","subhead","Wettbewerbssieger");const winners=add(target,"div","list");for(const winner of arr(item.wettbewerbssieger))winners.appendChild(row(winner.wettbewerb,winner.name));if(!winners.children.length)winners.appendChild(empty("Keine Wettbewerbssieger erfasst."));add(target,"h3","subhead","Saisonbestwerte");const best=add(target,"div","list");for(const record of arr(item.saisonbestwerte))best.appendChild(row(record.label,`${value(record)} · ${bestNames(record)}`));if(!best.children.length)best.appendChild(empty("Keine Saisonbestwerte erfasst."))}
function competitions(){const map=new Map();for(const s of arr(data.saisons))for(const w of arr(s.wettbewerbssieger)){const id=txt(w.wettbewerbId)||norm(w.wettbewerb);if(id&&!map.has(id))map.set(id,w.wettbewerb)}return [...map].map(([value,label])=>({value,label})).sort((a,b)=>a.label.localeCompare(b.label,"de"))}
function renderTitles(){const target=$("titleRows"),filter=$("competitionSelect").value,items=[];target.replaceChildren();for(const s of arr(data.saisons))for(const w of arr(s.wettbewerbssieger)){const id=txt(w.wettbewerbId)||norm(w.wettbewerb);if(!filter||id===filter)items.push({saison:s.label,wettbewerb:w.wettbewerb,name:w.name,punkte:w.punkte})}items.sort((a,b)=>b.saison.localeCompare(a.saison,"de"));if(!items.length){const tr=el("tr"),td=el("td","","Keine passenden Titel vorhanden.");td.colSpan=4;tr.appendChild(td);return target.appendChild(tr)}for(const item of items){const tr=el("tr");add(tr,"td","",item.saison);add(tr,"td","",item.wettbewerb);const cell=add(tr,"td");add(cell,"strong","",item.name);add(tr,"td","",item.punkte!==undefined?`${item.punkte} Punkte`:"–");target.appendChild(tr)}}
function people(){const map=new Map(),put=p=>{if(!txt(p?.name))return;const key=pkey(p);if(!map.has(key))map.set(key,{value:key,label:p.name})};for(const s of arr(data.saisons)){put(s.gesamtChampion);arr(s.wettbewerbssieger).forEach(put);for(const best of arr(s.saisonbestwerte)){if(arr(best.halter).length)best.halter.forEach(put);else put(best)}}for(const r of arr(data.ewigeRekorde))arr(r.halter).forEach(put);arr(data.ehrenchampions).forEach(put);return [...map.values()].sort((a,b)=>a.label.localeCompare(b.label,"de"))}
function renderPerson(){const target=$("personContent"),key=$("personSelect").value,items=[];target.replaceChildren();if(!key)return target.appendChild(empty("Mitglied auswählen, um alle archivierten Erfolge anzuzeigen."));for(const s of arr(data.saisons)){if(pkey(s.gesamtChampion)===key)items.push([s.label,"Gesamtchampion"]);for(const w of arr(s.wettbewerbssieger))if(pkey(w)===key)items.push([s.label,`Sieger ${w.wettbewerb}`]);for(const b of arr(s.saisonbestwerte)){const holders=arr(b.halter).length?b.halter:[b];if(holders.some(h=>pkey(h)===key))items.push([s.label,`${b.label}: ${value(b)}`])}}for(const h of arr(data.ehrenchampions))if(pkey(h)===key)items.push([h.saison||h.jahr,h.titel]);for(const r of arr(data.ewigeRekorde))for(const h of arr(r.halter))if(pkey(h)===key)items.push([h.saison||"Alle Saisons",`Absoluter Rekord: ${r.label} (${value(r)})`]);const list=el("div","list");for(const item of items)list.appendChild(row(item[0],item[1]));target.appendChild(items.length?list:empty("Für dieses Mitglied sind keine bestätigten Erfolge vorhanden."))}
async function load(){const response=await fetch("./ehrenlogbuch-archiv.json",{cache:"no-store"});if(!response.ok)throw Error("Archivdatei nicht erreichbar");data=await response.json();if(Number(data?.schemaVersion)!==1)throw Error("Unbekannte Archivversion");data.saisons=arr(data.saisons).filter(x=>x.status==="abgeschlossen").sort((a,b)=>txt(b.label).localeCompare(txt(a.label),"de"));renderHonors();renderRecords();fill($("seasonSelect"),data.saisons.map(x=>({value:x.id,label:`Saison ${x.label}`})),"Keine Saison verfügbar");if(data.saisons[0])$("seasonSelect").value=data.saisons[0].id;fill($("competitionSelect"),competitions(),"Alle Wettbewerbe");fill($("personSelect"),people(),"Mitglied auswählen");renderSeason();renderTitles();renderPerson();$("seasonSelect").addEventListener("change",renderSeason);$("competitionSelect").addEventListener("change",renderTitles);$("personSelect").addEventListener("change",renderPerson);$("dataStatus").textContent=data.meta?.hinweis||"Ehrenlogbuch geladen."}
window.TOSMCEhrenlogbuch={load};
})();
