name: Scheduler Smoke Test

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: read

jobs:
  scheduler-test:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduler-Test
        run: echo "scheduler-test"
